FROM ubuntu:16.04

MAINTAINER Vishwesh Ravi Shrimali <vishweshshrimali5@gmail.com>

ENV DEBIAN_FRONTEND noninteractive

# Setup Environment Variable
ENV cvVersionChoice=1
ENV cvVersion="3.4.1"
ENV cwd="/opt"

WORKDIR $cwd

RUN apt-get update && \
	apt-get remove -y \
	x264 libx264-dev && \
	apt-get install -y \
	build-essential \
	checkinstall \
	cmake \
	pkg-config \
	yasm \
	git \
	gfortran \
	libjpeg8-dev \
	libjasper-dev \
	libpng12-dev \
	libtiff5-dev \
	libtiff-dev \
	libavcodec-dev \
	libavformat-dev \
	libswscale-dev \
	libdc1394-22-dev \
	libxine2-dev \
	libv4l-dev \
	vim

RUN cd /usr/include/linux && \
	ln -s -f ../libv4l1-videodev.h videodev.h && \
	cd $cwd

RUN apt-get install -y \
	libgstreamer0.10-dev \
	libgstreamer-plugins-base0.10-dev \
	libgtk2.0-dev \
	libtbb-dev \
	qt5-default \
	libatlas-base-dev \
	libfaac-dev \
	libmp3lame-dev \
	libtheora-dev \
	libvorbis-dev \
	libxvidcore-dev \
	libopencore-amrnb-dev \
	libopencore-amrwb-dev \
	libavresample-dev \
	x264 \
	v4l-utils \
	libprotobuf-dev \
	protobuf-compiler \
	libgoogle-glog-dev \
	libgflags-dev \
	libgphoto2-dev \
	libeigen3-dev \
	libhdf5-dev \
	doxygen

RUN apt-get install -y wget && \
	wget https://repo.anaconda.com/archive/Anaconda3-5.2.0-Linux-x86_64.sh && \
	chmod u+x Anaconda3-5.2.0-Linux-x86_64.sh && \
	/bin/bash -c "./Anaconda3-5.2.0-Linux-x86_64.sh -b -p /opt/anaconda3 && \
	echo 'export PATH=\"/opt/anaconda3/bin:$PATH\"' >> ~/.bashrc && \
	source ~/.bashrc && \
	/opt/anaconda3/bin/conda create -y -f -n cling && \
	/opt/anaconda3/bin/conda install -y -n cling xeus-cling notebook -c QuantStack -c conda-forge && \
	/opt/anaconda3/bin/conda create -y -f -n OpenCV-\"$cvVersion\"-py2 python=2.7 anaconda && \
	/opt/anaconda3/bin/conda install -y -n OpenCV-\"$cvVersion\"-py2 numpy scipy matplotlib scikit-image scikit-learn ipython && \
	/opt/anaconda3/bin/conda create -y -f -n OpenCV-\"$cvVersion\"-py3 python=3.6 anaconda && \
	/opt/anaconda3/bin/conda install -y -n OpenCV-\"$cvVersion\"-py3 numpy scipy matplotlib scikit-image scikit-learn ipython && \
	/opt/anaconda3/bin/conda install -y -c conda-forge jupyterhub==0.8.1" && \
	rm Anaconda3-5.2.0-Linux-x86_64.sh

RUN ["/bin/bash", "-c", "source /root/.bashrc"]
ENV PATH /bin/anaconda3/bin:$PATH
ENV CONDA_DEFAULT_ENV OpenCV-"$cvVersion"-py2
ENV CONDA_PREFIX /opt/anaconda3/envs/OpenCV-"$cvVersion"-py2

RUN echo 'source activate OpenCV-"$cvVersion"-py2' >> ~/.bashrc && \
	echo 'python -m ipykernel install --name OpenCV-"$cvVersion"-py2 >> ~/.bashrc && \
	echo 'source deactivate' >> ~/.bashrc && \
	echo 'source activate OpenCV-"$cvVersion"-py3' >> ~/.bashrc && \
	echo 'python -m ipykernel install --name OpenCV-"$cvVersion"-py3 >> ~/.bashrc && \
	echo 'source deactivate' >> ~/.bashrc

ENV DEBIAN_FRONTEND teletype
